-- Généré par scripts/generate-seed.ts : ne pas modifier à la main.
begin;

-- Pays
insert into public.countries (name) values ('Algérie') on conflict do nothing;
insert into public.countries (name) values ('Belgique') on conflict do nothing;
insert into public.countries (name) values ('Burkina Faso') on conflict do nothing;
insert into public.countries (name) values ('Burundi') on conflict do nothing;
insert into public.countries (name) values ('Bénin') on conflict do nothing;
insert into public.countries (name) values ('Cameroun') on conflict do nothing;
insert into public.countries (name) values ('Canada') on conflict do nothing;
insert into public.countries (name) values ('Centrafrique') on conflict do nothing;
insert into public.countries (name) values ('Comores') on conflict do nothing;
insert into public.countries (name) values ('Congo') on conflict do nothing;
insert into public.countries (name) values ('Côte d''Ivoire') on conflict do nothing;
insert into public.countries (name) values ('Djibouti') on conflict do nothing;
insert into public.countries (name) values ('France') on conflict do nothing;
insert into public.countries (name) values ('Gabon') on conflict do nothing;
insert into public.countries (name) values ('Guinée') on conflict do nothing;
insert into public.countries (name) values ('Guinée équatoriale') on conflict do nothing;
insert into public.countries (name) values ('Haïti') on conflict do nothing;
insert into public.countries (name) values ('Luxembourg') on conflict do nothing;
insert into public.countries (name) values ('Madagascar') on conflict do nothing;
insert into public.countries (name) values ('Mali') on conflict do nothing;
insert into public.countries (name) values ('Maroc') on conflict do nothing;
insert into public.countries (name) values ('Maurice') on conflict do nothing;
insert into public.countries (name) values ('Mauritanie') on conflict do nothing;
insert into public.countries (name) values ('Niger') on conflict do nothing;
insert into public.countries (name) values ('RD Congo') on conflict do nothing;
insert into public.countries (name) values ('Rwanda') on conflict do nothing;
insert into public.countries (name) values ('Seychelles') on conflict do nothing;
insert into public.countries (name) values ('Suisse') on conflict do nothing;
insert into public.countries (name) values ('Sénégal') on conflict do nothing;
insert into public.countries (name) values ('Tchad') on conflict do nothing;
insert into public.countries (name) values ('Togo') on conflict do nothing;
insert into public.countries (name) values ('Tunisie') on conflict do nothing;

-- Villes autorisées (liste officielle)
insert into public.allowed_cities (name, country) values ('Alger', 'Algérie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Oran', 'Algérie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Constantine', 'Algérie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Annaba', 'Algérie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Blida', 'Algérie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bruxelles', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Liège', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Charleroi', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Namur', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mons', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Anvers', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Gand', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Cotonou', 'Bénin') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Porto-Novo', 'Bénin') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Parakou', 'Bénin') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Abomey-Calavi', 'Bénin') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Djougou', 'Bénin') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Ouagadougou', 'Burkina Faso') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bobo-Dioulasso', 'Burkina Faso') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Koudougou', 'Burkina Faso') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Banfora', 'Burkina Faso') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bujumbura', 'Burundi') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Gitega', 'Burundi') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Douala', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Yaoundé', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bafoussam', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Garoua', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bamenda', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Maroua', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Ngaoundéré', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kribi', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Limbé', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Montréal', 'Canada') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Québec', 'Canada') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Gatineau', 'Canada') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Laval', 'Canada') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sherbrooke', 'Canada') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Ottawa', 'Canada') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Moncton', 'Canada') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bangui', 'Centrafrique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bimbo', 'Centrafrique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Berbérati', 'Centrafrique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Carnot', 'Centrafrique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bambari', 'Centrafrique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Moroni', 'Comores') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mutsamudu', 'Comores') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Brazzaville', 'Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Pointe-Noire', 'Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Dolisie', 'Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nkayi', 'Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Abidjan', 'Côte d''Ivoire') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bouaké', 'Côte d''Ivoire') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Yamoussoukro', 'Côte d''Ivoire') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('San-Pédro', 'Côte d''Ivoire') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Daloa', 'Côte d''Ivoire') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Korhogo', 'Côte d''Ivoire') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Djibouti', 'Djibouti') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Paris', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Marseille', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lyon', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lille', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Toulouse', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nice', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nantes', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Strasbourg', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Montpellier', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bordeaux', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Rennes', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Reims', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Le Havre', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Saint-Étienne', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Toulon', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Grenoble', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Dijon', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Angers', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nîmes', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Villeurbanne', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Clermont-Ferrand', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Le Mans', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Aix-en-Provence', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Brest', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Tours', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Amiens', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Limoges', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Metz', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Perpignan', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Besançon', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Orléans', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Rouen', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mulhouse', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Caen', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nancy', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Saint-Denis', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Montreuil', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Argenteuil', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Roubaix', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Tourcoing', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Créteil', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Cergy', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sarcelles', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Pointe-à-Pitre', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Fort-de-France', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Cayenne', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Saint-Denis (La Réunion)', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mamoudzou', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Libreville', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Port-Gentil', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Franceville', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Oyem', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Moanda', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lambaréné', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mouila', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Conakry', 'Guinée') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nzérékoré', 'Guinée') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kankan', 'Guinée') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kindia', 'Guinée') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Labé', 'Guinée') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Malabo', 'Guinée équatoriale') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bata', 'Guinée équatoriale') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Port-au-Prince', 'Haïti') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Cap-Haïtien', 'Haïti') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Gonaïves', 'Haïti') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Les Cayes', 'Haïti') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Pétion-Ville', 'Haïti') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Luxembourg', 'Luxembourg') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Esch-sur-Alzette', 'Luxembourg') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Antananarivo', 'Madagascar') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Toamasina', 'Madagascar') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Antsirabe', 'Madagascar') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mahajanga', 'Madagascar') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Fianarantsoa', 'Madagascar') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Toliara', 'Madagascar') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bamako', 'Mali') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sikasso', 'Mali') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Ségou', 'Mali') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mopti', 'Mali') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kayes', 'Mali') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Casablanca', 'Maroc') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Rabat', 'Maroc') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Marrakech', 'Maroc') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Fès', 'Maroc') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Tanger', 'Maroc') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Agadir', 'Maroc') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Port-Louis', 'Maurice') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Curepipe', 'Maurice') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nouakchott', 'Mauritanie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Nouadhibou', 'Mauritanie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Niamey', 'Niger') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Zinder', 'Niger') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Maradi', 'Niger') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Agadez', 'Niger') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Tahoua', 'Niger') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kinshasa', 'RD Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lubumbashi', 'RD Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Mbuji-Mayi', 'RD Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kisangani', 'RD Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Goma', 'RD Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bukavu', 'RD Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kananga', 'RD Congo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kigali', 'Rwanda') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Huye', 'Rwanda') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Dakar', 'Sénégal') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Thiès', 'Sénégal') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Saint-Louis', 'Sénégal') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Touba', 'Sénégal') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Ziguinchor', 'Sénégal') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kaolack', 'Sénégal') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Victoria', 'Seychelles') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Genève', 'Suisse') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lausanne', 'Suisse') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Fribourg', 'Suisse') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Neuchâtel', 'Suisse') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sion', 'Suisse') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('N''Djamena', 'Tchad') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Moundou', 'Tchad') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sarh', 'Tchad') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Abéché', 'Tchad') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kélo', 'Tchad') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lomé', 'Togo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sokodé', 'Togo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kara', 'Togo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kpalimé', 'Togo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Atakpamé', 'Togo') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Tunis', 'Tunisie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sfax', 'Tunisie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Sousse', 'Tunisie') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Paris', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Marseille', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lyon', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Lille', 'France') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Bruxelles', 'Belgique') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Abidjan', 'Côte d''Ivoire') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Libreville', 'Gabon') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Douala', 'Cameroun') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Dakar', 'Sénégal') on conflict do nothing;
insert into public.allowed_cities (name, country) values ('Kinshasa', 'RD Congo') on conflict do nothing;

-- Villes ouvertes au lancement
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Paris', 'France', 'open', false, '#FF5CA8', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Marseille', 'France', 'open', false, '#FF7A1F', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Lyon', 'France', 'open', false, '#C8F53C', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Lille', 'France', 'open', false, '#9B6BFF', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Bruxelles', 'Belgique', 'open', false, '#2F4BFF', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Abidjan', 'Côte d''Ivoire', 'open', false, '#FF7A1F', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Libreville', 'Gabon', 'open', false, '#C8F53C', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Douala', 'Cameroun', 'open', false, '#FF5CA8', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Dakar', 'Sénégal', 'open', false, '#9B6BFF', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;
insert into public.cities (name, country, status, pioneer, color, opened_at) values ('Kinshasa', 'RD Congo', 'open', false, '#2F4BFF', now()) on conflict (name, country) do update set status = 'open', color = excluded.color;

-- Expressions
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('wesh', 'Wesh', 'France', 'Argot', 'eu', 'salut', 'Salut ! Sert aussi à interpeller quelqu''un ou à marquer la surprise.', '« Wesh, bien ou quoi ? »', '@kenza.lyon') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('enjailler', 'S''enjailler', 'Abidjan', 'Nouchi', 'af', 's''amuser, faire la fête', 'S''amuser, faire la fête. Né en Côte d''Ivoire, repris partout en France.', '« Vendredi, on s''enjaille chez Awa. »', '@awa_225') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('seum', 'Le seum', 'Paris', 'Argot', 'eu', 'être dégoûté', 'Avoir le seum : être dégoûté, frustré, rageux.', '« Il a raté son bus de 10 secondes, il a le seum. »', '@yanis93') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('degun', 'Dégun', 'Marseille', 'Parler marseillais', 'eu', 'personne', 'Personne. Typique de Marseille et du Sud.', '« Plage à 7 h, y a dégun. »', '@lea.13') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('ondit', 'On dit quoi ?', 'Douala', 'Camfranglais', 'af', 'salut, quoi de neuf ?', 'Salut, ça va, quoi de neuf ? Salutation courante au Cameroun.', '« Eh gars, on dit quoi ? »', '@franck.dla') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('savoir', 'Tu sais venir ?', 'Bruxelles', 'Belgicisme', 'eu', 'tu peux venir ?', 'En Belgique, « savoir » s’utilise souvent pour « pouvoir ».', '« Tu sais me passer le sel ? »', '@manon.bxl') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('mbolo', 'Mbolo', 'Libreville', 'Fang', 'af', 'bonjour', 'Bonjour, salut. Vient du fang, utilisé partout au Gabon.', '« Mbolo la famille ! »', '@ndong.lbv') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('askip', 'Askip', 'France', 'Internet', 'web', 'à ce qu''il paraît', 'À ce qu''il paraît. La contraction qui a conquis les messageries.', '« Askip il déménage. »', '@ines.sms') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('chelou', 'Chelou', 'France', 'Verlan', 'eu', 'bizarre', '« Louche » à l’envers : bizarre, suspect.', '« Ce bruit est chelou. »', '@theo.verlan') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('mbote', 'Mbote', 'Kinshasa', 'Lingala', 'af', 'bonjour', 'Bonjour, en lingala. On le dit à Kinshasa comme à Brazzaville.', '« Mbote na bino ! »', '@grace.kin') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('pls', 'En PLS', 'France', 'Internet', 'web', 'au plus mal', 'Au plus mal, abattu. Vient de la « position latérale de sécurité ».', '« Après l''exam, je suis en PLS. »', '@sarah.pls') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('daron', 'Daron', 'France', 'Argot', 'eu', 'le père', 'Le père. La daronne : la mère. Les darons : les parents.', '« Mon daron m''appelle. »', 'l’équipe') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('carre', 'C''est carré', 'France', 'Argot', 'eu', 'c''est réglé, nickel', 'C''est réglé, c''est nickel, rien à redire.', '« Le plan pour samedi ? C''est carré. »', 'l’équipe') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('nangadef', 'Nanga def', 'Dakar', 'Wolof', 'af', 'comment ça va ?', 'Comment ça va ? La salutation de base en wolof.', '« Nanga def ? Maa ngi fi. »', '@moussa.dkr') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('balle', 'De la balle', 'Darons', 'Années 90', 'darons', 'génial', 'Génial. Le « trop bien » des années 90.', '« Ce jeu est de la balle ! »', 'l’équipe') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('chanme', 'Chanmé', 'Darons', 'Verlan 2000', 'darons', 'génial', '« Méchant » en verlan, qui veut dire… génial.', '« Ton son est chanmé. »', 'l’équipe') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('ramasse', 'À la ramasse', 'Darons', 'Argot', 'darons', 'largué', 'Largué, à côté de la plaque.', '« Le lundi matin, je suis à la ramasse. »', 'l’équipe') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('pied', 'C''est le pied', 'Darons', 'Expression', 'darons', 'c''est génial', 'C''est génial, c''est le top.', '« Des vacances à la mer, c''est le pied. »', 'l’équipe') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('peche', 'Avoir la pêche', 'Darons', 'Expression', 'darons', 'être en forme', 'Être plein d''énergie.', '« T''as la pêche ce matin ! »', 'l’équipe') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('mbenguiste', 'Mbenguiste', 'Douala', 'Camfranglais', 'af', 'qui vit en Europe', 'Quelqu''un qui vit en Europe, le « mbeng ».', '« Mon cousin est mbenguiste depuis 5 ans. »', '@franck.dla') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;
insert into public.expressions (key, word, place, lang, region, mean, def, ex, author_label) values ('cestcomment', 'C''est comment ?', 'Abidjan', 'Nouchi', 'af', 'ça va ?', 'Ça va ? Qu''est-ce qui se passe ? On l''entend partout en Afrique de l''Ouest.', '« Eh, c''est comment ? »', '@awa_225') on conflict (key) do update set word = excluded.word, def = excluded.def, ex = excluded.ex, mean = excluded.mean;

-- Questions
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-enjailler', 'enjailler', '« On va s''enjailler ce soir »', array['On va s''ennuyer', 'On va bien s''amuser', 'On va se disputer', 'On va rentrer tôt']::text[], 1, 'ça se passe plutôt le soir, avec du son.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-seum', 'seum', '« J''ai trop le seum »', array['J''ai trop faim', 'Je suis fatigué', 'J''ai de la chance', 'Je suis dégoûté']::text[], 3, 'on l’a souvent après une défaite.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-degun', 'degun', '« Ce matin, y a dégun »', array['Il y a du monde', 'Il fait beau', 'Il n''y a personne', 'Il y a un souci']::text[], 2, 'parfait pour une plage tranquille.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-ondit', 'ondit', '« On dit quoi ? »', array['Répète, j''ai pas entendu', 'Salut, quoi de neuf ?', 'Tu parles de quoi ?', 'On se tait']::text[], 1, 'c’est comme ça qu’on démarre une discussion.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-savoir', 'savoir', '« Tu sais venir demain ? »', array['Tu connais le chemin ?', 'Tu veux venir ?', 'Tu as su pour demain ?', 'Tu peux venir demain ?']::text[], 3, 'en Belgique, savoir, c’est un peu pouvoir.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-mbolo', 'mbolo', '« Mbolo ! »', array['Bonjour !', 'Au revoir !', 'Merci !', 'Bonne nuit !']::text[], 0, 'on le dit en arrivant.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-askip', 'askip', '« Askip il déménage »', array['Il déménage à coup sûr', 'Il ne déménage plus', 'Il paraît qu''il déménage', 'Il déménage vite']::text[], 2, 'c’est une rumeur.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-chelou', 'chelou', '« Ce bruit est chelou »', array['Il est cher', 'Il est bizarre', 'Il est chaud', 'Il est charmant']::text[], 1, 'lis-le à l’envers.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-mbote', 'mbote', '« Mbote ! »', array['Merci !', 'Viens !', 'Doucement !', 'Bonjour !']::text[], 3, 'même idée que « Mbolo ».') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-pls', 'pls', '« Après l''exam, je suis en PLS »', array['Je suis au top', 'Je suis au plus mal', 'Je suis en vacances', 'Je suis en retard']::text[], 1, 'pense aux gestes de premiers secours.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-wesh', 'wesh', '« Wesh, bien ou quoi ? »', array['Salut, ça va ?', 'Tais-toi', 'Au revoir', 'Tu es sûr ?']::text[], 0, 'on l’entend dix fois par jour.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-daron', 'daron', '« Mon daron arrive »', array['Mon patron', 'Mon père', 'Mon voisin', 'Mon chien']::text[], 1, 'il est de la famille.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-carre', 'carre', '« Pour samedi, c''est carré »', array['C''est annulé', 'C''est compliqué', 'C''est réglé', 'C''est trop tard']::text[], 2, 'tout est calé.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-nangadef', 'nangadef', '« Nanga def ? »', array['Tu viens d''où ?', 'Comment ça va ?', 'Tu as faim ?', 'Il est quelle heure ?']::text[], 1, 'on répond « Maa ngi fi ».') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-mbenguiste', 'mbenguiste', '« Mon cousin est mbenguiste »', array['Il est musicien', 'Il vit en Europe', 'Il est très riche', 'Il est mécanicien']::text[], 1, 'le « mbeng », c’est loin du Cameroun.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-cestcomment', 'cestcomment', '« Eh, c''est comment ? »', array['Ça va ?', 'C''est combien ?', 'C''est où ?', 'C''est quand ?']::text[], 0, 'une façon de saluer.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-balle', 'balle', '« C''est de la balle ! »', array['C''est du sport', 'C''est dangereux', 'C''est génial', 'C''est tout rond']::text[], 2, 'tes parents le disaient quand ils kiffaient.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-chanme', 'chanme', '« C''est chanmé »', array['C''est génial', 'C''est pas cher', 'C''est mâché', 'C''est la chance']::text[], 0, 'c’est du verlan.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-ramasse', 'ramasse', '« Il est à la ramasse »', array['Il fait le ménage', 'Il est très riche', 'Il est hyper organisé', 'Il est largué']::text[], 3, 'pas vraiment un compliment.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-pied', 'pied', '« Ce concert, c''est le pied ! »', array['Ça fait mal aux pieds', 'C''est génial', 'C''est trop loin', 'Il faut danser']::text[], 1, 'rien à voir avec les chaussures.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;
insert into public.questions (id, lex, expr, answers, good, hint) values ('q-peche', 'peche', '« T''as la pêche ce matin ! »', array['Tu es en forme', 'Tu as faim', 'Tu vas pêcher', 'Tu es en colère']::text[], 0, 'plein d’énergie.') on conflict (id) do update set expr = excluded.expr, answers = excluded.answers, good = excluded.good, hint = excluded.hint;

commit;
